name: Android Lint
run-name: Running Android Lint

on:
  pull_request:
    branches:
      - 'development'

jobs:
  android-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java SDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          
      - run: ./gradlew lint
        
      - uses: yutailang0119/action-android-lint@v4
        with:
          report-path: build/reports/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
          ignore-warnings: true # Ignore Lint Warnings
        continue-on-error: false # If annotations contain error of severity, action-android-lint exit 1.
